theme: jekyll-theme-minimal
title: New title here
description: My webpage
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: PZA uptake
    url: pza
